db:
  extends:
    file: docker-compose.yml
    service: db

cache:
  extends:
    file: docker-compose.yml
    service: cache

www:
  image: phase2/apache24php55
  environment:
    PHP_XDEBUG: "true"
    PHP_XHPROF: "true"
    VIRTUAL_HOST: drupal-ci-test.ci.p2devcloud.com
  links:
    - db
    - cache
  volumes:
    - .:/code/
    - ./build/html:/var/www/html
    - /data/drupal-ci-test/files:/var/www/html/sites/default/files
